Merry Christmas everyone! 

[Advent of Code day 11](http://adventofcode.com/2018/day/11)

In [1]:
import numpy as np

## Part 1

Hmmm... not sure that this will take long to generate the actual grid, so maybe just do a naïve run at it first:

In [2]:
def get_hundreds(i):
    "Return number of hundreds in i"
    return int(str(i).zfill(3)[-3])

In [3]:
grid_ar=np.zeros([300, 300], dtype=np.int)

grid_ar

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

Add the rack IDs:

In [4]:
rack_id_ar=np.array([[10+i for i in range(1, 301)]] * 300)

grid_ar+=rack_id_ar
grid_ar

array([[ 11,  12,  13, ..., 308, 309, 310],
       [ 11,  12,  13, ..., 308, 309, 310],
       [ 11,  12,  13, ..., 308, 309, 310],
       ..., 
       [ 11,  12,  13, ..., 308, 309, 310],
       [ 11,  12,  13, ..., 308, 309, 310],
       [ 11,  12,  13, ..., 308, 309, 310]])

In [5]:
np.array([[10+i for i in range(1, 301)]] * 300)

array([[ 11,  12,  13, ..., 308, 309, 310],
       [ 11,  12,  13, ..., 308, 309, 310],
       [ 11,  12,  13, ..., 308, 309, 310],
       ..., 
       [ 11,  12,  13, ..., 308, 309, 310],
       [ 11,  12,  13, ..., 308, 309, 310],
       [ 11,  12,  13, ..., 308, 309, 310]])

Multiply the rack ID by the Y coordinate

In [6]:
y_coordinates_ar=np.array([[i]*300 for i in range(1, 301)])

y_coordinates_ar

array([[  1,   1,   1, ...,   1,   1,   1],
       [  2,   2,   2, ...,   2,   2,   2],
       [  3,   3,   3, ...,   3,   3,   3],
       ..., 
       [298, 298, 298, ..., 298, 298, 298],
       [299, 299, 299, ..., 299, 299, 299],
       [300, 300, 300, ..., 300, 300, 300]])

In [7]:
grid_ar*=y_coordinates_ar
grid_ar

array([[   11,    12,    13, ...,   308,   309,   310],
       [   22,    24,    26, ...,   616,   618,   620],
       [   33,    36,    39, ...,   924,   927,   930],
       ..., 
       [ 3278,  3576,  3874, ..., 91784, 92082, 92380],
       [ 3289,  3588,  3887, ..., 92092, 92391, 92690],
       [ 3300,  3600,  3900, ..., 92400, 92700, 93000]])

Add the serial number

In [8]:
test_serial_number=8

grid_ar+=test_serial_number

grid_ar

array([[   19,    20,    21, ...,   316,   317,   318],
       [   30,    32,    34, ...,   624,   626,   628],
       [   41,    44,    47, ...,   932,   935,   938],
       ..., 
       [ 3286,  3584,  3882, ..., 91792, 92090, 92388],
       [ 3297,  3596,  3895, ..., 92100, 92399, 92698],
       [ 3308,  3608,  3908, ..., 92408, 92708, 93008]])

Multiply again by the rack ID:

In [9]:
grid_ar*=rack_id_ar

In [10]:
grid_ar[4][2]

949

Apply the `get_hundreds` function to the array:

In [11]:
np.vectorize(get_hundreds)(grid_ar)

array([[2, 2, 2, ..., 3, 9, 5],
       [3, 3, 4, ..., 1, 4, 6],
       [4, 5, 6, ..., 0, 9, 7],
       ..., 
       [1, 0, 4, ..., 9, 8, 2],
       [2, 1, 6, ..., 8, 2, 3],
       [3, 2, 8, ..., 6, 7, 4]])

And subtract 5:

In [12]:
ar=_-5

In [13]:
ar[4][2]

4

OK, let's put all that into a single function:

In [14]:
def generate_fuel_cells(serial_number):
    '''Generates grid of fuel cells'''
    rack_id_ar=np.array([[10+i for i in range(1, 301)]] * 300)
    y_coordinates_ar=np.array([[i]*300 for i in range(1, 301)])
    
    
    grid_out_ar=np.zeros([300, 300], dtype=np.int)
    grid_out_ar+=rack_id_ar
    grid_out_ar*=y_coordinates_ar
    grid_out_ar+=serial_number
    grid_out_ar*=rack_id_ar
    grid_out_ar=np.vectorize(get_hundreds)(grid_out_ar)
    grid_out_ar-=5
    
    # And I'll return the transpose so that the coordinates
    # match to X and Y
    return grid_out_ar.T
    
    

When calling the grid, remember that the grid dimensions are offset by 1.

In [15]:
assert generate_fuel_cells(8)[2,4]==4
assert generate_fuel_cells(57)[121, 78]==-5
assert generate_fuel_cells(39)[216, 195]==0
assert generate_fuel_cells(71)[100, 152]==4

OK, good. Now find the smallest 3\*3 subgrid.

We can use `sum(sum(...))` to get the sum of all the members of the grid, as with:

In [16]:
ar=generate_fuel_cells(18)
ar[4:7, 6:9]

array([[ 3, -5, -3],
       [-5, -2,  0],
       [-2,  1,  4]])

In [17]:
ar=generate_fuel_cells(18)
sum(sum(ar[4:7, 6:9]))

-9

Good, so now we can just use `max`:

In [18]:
# Add x+1 and y+1 to make it easier to read:

max([(sum(sum(ar[x:x+3,y:y+3])), x+1, y+1) for x in range(300) for y in range(300)])

(29, 33, 45)

Check the results:

In [19]:
ar=generate_fuel_cells(18)
assert max([(sum(sum(ar[x:x+3,y:y+3])), x+1, y+1) for x in range(300) for y in range(300)]) == (29, 33, 45)

ar=generate_fuel_cells(42)
assert max([(sum(sum(ar[x:x+3,y:y+3])), x+1, y+1) for x in range(300) for y in range(300)]) == (30, 21, 61)



OK, those work. So for my puzzle input of 9445, have:

In [20]:
ar=generate_fuel_cells(9445)
max([(sum(sum(ar[x:x+3,y:y+3])), x+1, y+1) for x in range(300) for y in range(300)])

(29, 233, 36)

Yep, that looks like it. 

## Part 2

Shouldn't be too hard, although as usual I'll brute force it in the first instance.

Wrap it in a function (put in the grid as an input: don't want to keep reconstructing it)

In [21]:
def get_maximum_grid(input_grid, subgrid_size):
    '''
    Return the coordinates and size of highest 
    power subgrid of size subgrid_size
    '''
    # Check that the input's the right size
    assert input_grid.size==90000
    
    return max([(sum(sum(input_grid[x:x+subgrid_size,y:y+subgrid_size])), x+1, y+1) 
                for x in range(300-subgrid_size) for y in range(300-subgrid_size)])

In [22]:
ar=generate_fuel_cells(42)

In [23]:
get_maximum_grid(ar, 3)

(30, 21, 61)

Hmmm... that's interesting. Looks like it peaks quite early, then goes heavily negative. Let's just assume that if the maximum is negative, then we've found the global max. Might not work and I don't have the time or inclination to prove it, but let's give it a go.

In [24]:
def global_max(serial_number):
    '''Return the global max serial number, with the coords and subgrid size'''
    fuel_array=generate_fuel_cells(serial_number)
    
    current_subgrid_size=1
    global_max=0
    current_max=1
    
    while current_max>=0:
        (current_max, x, y)=get_maximum_grid(fuel_array, current_subgrid_size)
        if current_max>global_max:
            global_max=current_max
            max_x=x
            max_y=y
            max_s=current_subgrid_size
        current_subgrid_size+=1
    
    return (global_max, max_x, max_y, max_s)
            
        
        
        



In [25]:
ar=generate_fuel_cells(18)

get_maximum_grid(ar, 3)
global_max(18)

(113, 90, 269, 16)

That seems to be working. Also do a check for 42:

In [26]:
assert global_max(18)[1:4]==(90,269,16)
assert global_max(42)[1:4]==(232,251,12)

And finally with the test input:

In [27]:
global_max(9445)[1:4]

(231, 107, 14)

Done.